/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Common String Algorithm
 #	author : miyako
 #	2013/09/03
 #
 # --------------------------------------------------------------------------------*/



// --- Dice's coefficient
void Coefficient(sLONG_PTR *pResult, PackagePtr pParams);

// --- Levenshtein distance
void Levenshtein(sLONG_PTR *pResult, PackagePtr pParams);

// --- LCS
void Longest_common_subsequence(sLONG_PTR *pResult, PackagePtr pParams);
void Longest_common_substring(sLONG_PTR *pResult, PackagePtr pParams);

// --- Jaro Winkler
void Jaro_winkler(sLONG_PTR *pResult, PackagePtr pParams);
void Jaro(sLONG_PTR *pResult, PackagePtr pParams);
